# Generated by Django 4.0.6 on 2022-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.CharField(max_length=15)),
                ('second_text', models.CharField(max_length=50)),
                ('thirst_text', models.CharField(max_length=50)),
            ],
        ),
    ]
