# Generated by Django 4.0.6 on 2022-07-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Commercials',
        ),
    ]
